---
directory: third-party
hooks: [config/python/userfs/hooks]

projects:
  crosstool-ng:
    source: github
    path: crosstool-ng
    fetch:
      branch: master
      single-branch: true
      depth: 1
